# Generated by Django 6.0.6 on 2026-08-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='words',
            field=models.JSONField(default=list),
        ),
    ]
